services:
  db:
    image: postgres:16
    container_name: temizsepet_postgres
    environment:
      POSTGRES_DB: temizsepet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - temizsepet_pgdata:/var/lib/postgresql/data

volumes:
  temizsepet_pgdata:
