"""Kullanıcı profilindeki alerjen anahtarları → içerik metninde geçebilecek karşılıklar.

Tam eşleşme substring ile yapılır; yazım kayması için bkz. `services/scoring` fuzzy token eşlemesi.
SYNONYMS anahtarları `_normalize` ile aranır (`casefold` uyumlu küçük harf).
"""

SYNONYMS: dict[str, list[str]] = {
  'laktoz': [
    'lactose',
    'inek sütü',
    'süt ürünü',
    'süt yağı',
    'süt proteini',
    'peynir altı suyu',
    'whey',
    'whey protein',
    'milk',
    'milk powder',
    'milk fat',
    'kazein',
    'casein',
    'tereyağı',
    'kaymak',
    'peynir',
    'yoğurt',
    'laktalbumin',
    'laktoglobulin',
  ],
  'gluten': [
    'buğday',
    'arpa',
    'çavdar',
    'yulaf',
    'bulgur',
    'irmik',
    'buğday unu',
    'arpa unu',
    'çavdar unu',
    'yulaf unu',
    'malt',
    'malt özü',
    'malt extract',
    'wheat',
    'barley',
    'rye',
    'oats',
    'kamut',
    'spelt',
    'triticale',
  ],
  'yumurta': [
    'egg',
    'eggs',
    'albumin',
    'lysozyme',
    'ovoalbumin',
    'mayonez',
  ],
  'soya': [
    'soy',
    'soya fasulyesi',
    'soya proteini',
    'soya lesitini',
    'soya lecithin',
    'tofu',
    'edamame',
  ],
  'yer fıstığı': [
    'peanut',
    'peanuts',
    'arachis',
    'groundnut',
  ],
  'kabuklu yemiş': [
    'badem',
    'fındık',
    'ceviz',
    'kaju',
    'pistachio',
    'pistachios',
    'pecan',
    'macadamia',
    'shea nut',
    'sheanut',
  ],
  'kereviz': [
    'celeriac',
    'celery',
    'sellerie',
  ],
  'hardal': [
    'mustard',
    'mustarda',
  ],
  'susam': [
    'sesame',
    'sesame seed',
    'tahin',
    'tahini',
  ],
  'balık': [
    'fish',
    'balık jölesi',
    'fish gelatin',
    'anchovy',
    'hamsi',
    'ton balığı',
    'somon',
  ],
  'kabuklu deniz ürünleri': [
    'shellfish',
    'karides',
    'yengeç',
    'ıstakoz',
    'midye',
    'istiridye',
    'squid',
    'kalamar',
  ],
}